import type { Metadata } from "next";
import { Inter, Karla } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import { AuthProvider } from '../../context/AuthContext';

const inter = Inter({ subsets: ["latin"] });
const karla = Karla({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} ${karla.className}`}>
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
